#pragma once

#include <MediaZ/PluginAPI.h>
#include <MediaZ/Helpers.hpp>


MZ_REGISTER_NAME(Device);
MZ_REGISTER_NAME(ReferenceSource);
MZ_REGISTER_NAME(Debug);
MZ_REGISTER_NAME_SPACED(Dispatch_Size, "Dispatch Size");
MZ_REGISTER_NAME_SPACED(Shader_Type, "Shader Type");

MZ_REGISTER_NAME(AJA_RGB2YCbCr_Compute_Shader);
MZ_REGISTER_NAME(AJA_YCbCr2RGB_Compute_Shader);
MZ_REGISTER_NAME(AJA_RGB2YCbCr_Shader);
MZ_REGISTER_NAME(AJA_YCbCr2RGB_Shader);
MZ_REGISTER_NAME(AJA_RGB2YCbCr_Compute_Pass);
MZ_REGISTER_NAME(AJA_YCbCr2RGB_Compute_Pass);
MZ_REGISTER_NAME(AJA_RGB2YCbCr_Pass);
MZ_REGISTER_NAME(AJA_YCbCr2RGB_Pass);

MZ_REGISTER_NAME(Colorspace);
MZ_REGISTER_NAME(Source);
MZ_REGISTER_NAME(Interlaced);
MZ_REGISTER_NAME(ssbo);
MZ_REGISTER_NAME(Output);

MZ_REGISTER_NAME_SPACED(AJA_AJAIn, "AJA.AJAIn");
MZ_REGISTER_NAME_SPACED(AJA_AJAOut, "AJA.AJAOut");