#pragma once

#include <Nodos/PluginAPI.h>
#include <Nodos/Helpers.hpp>


NOS_REGISTER_NAME(Device);
NOS_REGISTER_NAME(ReferenceSource);
NOS_REGISTER_NAME(Debug);
NOS_REGISTER_NAME_SPACED(Dispatch_Size, "Dispatch Size");
NOS_REGISTER_NAME_SPACED(Shader_Type, "Shader Type");

NOS_REGISTER_NAME(AJA_RGB2YCbCr_Compute_Shader);
NOS_REGISTER_NAME(AJA_YCbCr2RGB_Compute_Shader);
NOS_REGISTER_NAME(AJA_RGB2YCbCr_Shader);
NOS_REGISTER_NAME(AJA_YCbCr2RGB_Shader);
NOS_REGISTER_NAME(AJA_RGB2YCbCr_Compute_Pass);
NOS_REGISTER_NAME(AJA_YCbCr2RGB_Compute_Pass);
NOS_REGISTER_NAME(AJA_RGB2YCbCr_Pass);
NOS_REGISTER_NAME(AJA_YCbCr2RGB_Pass);

NOS_REGISTER_NAME(Colorspace);
NOS_REGISTER_NAME(Source);
NOS_REGISTER_NAME(Interlaced);
NOS_REGISTER_NAME(ssbo);
NOS_REGISTER_NAME(Output);

NOS_REGISTER_NAME_SPACED(AJA_AJAIn, "AJA.AJAIn");
NOS_REGISTER_NAME_SPACED(AJA_AJAOut, "AJA.AJAOut");