#ifndef _INTERLACED_FLAGS_H
#define _INTERLACED_FLAGS_H

#define MZ_AJA_OUT_OUTPUT_EVEN_FIELD_MASK 1
#define MZ_AJA_OUT_OUTPUT_ODD_FIELD_MASK 2
#define MZ_AJA_OUT_OUTPUT_INTERLACED_MASK 3
#define MZ_AJA_OUT_INPUT_EVEN_FIELD_MASK 4
#define MZ_AJA_OUT_INPUT_ODD_FIELD_MASK 8
#define MZ_AJA_OUT_INPUT_INTERLACED_MASK 12
#define MZ_AJA_OUT_COMP10_MASK 16

#endif